# 基础镜像
FROM redis
# author
MAINTAINER yozu

# 挂载目录
VOLUME /home/yozu/redis
# 创建目录
RUN mkdir -p /home/yozu/redis
# 指定路径
WORKDIR /home/yozu/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/yozu/redis/redis.conf
