# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER yozu

# 挂载目录
VOLUME /home/yozu
# 创建目录
RUN mkdir -p /home/yozu
# 指定路径
WORKDIR /home/yozu
# 复制jar文件到路径
COPY ./jar/yozu-visual-monitor.jar /home/yozu/yozu-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","yozu-visual-monitor.jar"]
